// <auto-generated />
using System;
using AvatarManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AvatarManagement.Migrations
{
    [DbContext(typeof(AvatarManagementDbContext))]
    [Migration("20210926205609_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Entities.AvatarManagement.Animation", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AvatarId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Change")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdleStateAnimationTimer")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Insertion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<string>("Src")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Animation");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9fa06f6c-5525-4fb3-ab0e-3261c8545bdd"),
                            AvatarId = new Guid("d609e9e5-0ce2-4e52-86a8-0fc0455955c7"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdleStateAnimationTimer = 100,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 898, DateTimeKind.Utc).AddTicks(338),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Src = "profile"
                        });
                });

            modelBuilder.Entity("Entities.AvatarManagement.AnimationState", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Change")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Insertion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnimationId");

                    b.ToTable("AnimationState");

                    b.HasData(
                        new
                        {
                            Id = new Guid("76897c6a-1fc6-44e0-b426-ab78adbddec0"),
                            AnimationId = new Guid("9fa06f6c-5525-4fb3-ab0e-3261c8545bdd"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Index = 0,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 898, DateTimeKind.Utc).AddTicks(7249),
                            Name = "IDLE",
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("4f97aeac-eb45-43ad-8ff6-7b50f76b1114"),
                            AnimationId = new Guid("9fa06f6c-5525-4fb3-ab0e-3261c8545bdd"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Index = 1,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 901, DateTimeKind.Utc).AddTicks(7848),
                            Name = "FRONT",
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("98bb3714-f46d-47a1-b5d8-804565647227"),
                            AnimationId = new Guid("9fa06f6c-5525-4fb3-ab0e-3261c8545bdd"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Index = 2,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 903, DateTimeKind.Utc).AddTicks(2488),
                            Name = "BACK",
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("82b4d763-783b-4021-adca-8006ca1dba9b"),
                            AnimationId = new Guid("9fa06f6c-5525-4fb3-ab0e-3261c8545bdd"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Index = 3,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 904, DateTimeKind.Utc).AddTicks(7015),
                            Name = "RIGHT",
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("c5e30e70-49b3-41dd-8810-c22f7fb65241"),
                            AnimationId = new Guid("9fa06f6c-5525-4fb3-ab0e-3261c8545bdd"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Index = 4,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 906, DateTimeKind.Utc).AddTicks(1461),
                            Name = "LEFT",
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Entities.AvatarManagement.AnimationStateItem", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimationStateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Change")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("H")
                        .HasColumnType("integer");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Insertion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<int>("W")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimationStateId");

                    b.ToTable("AnimationStateItem");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ba53bf19-8986-48b0-b2b8-398a0ac3604a"),
                            AnimationStateId = new Guid("76897c6a-1fc6-44e0-b426-ab78adbddec0"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 0,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 899, DateTimeKind.Utc).AddTicks(4205),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 25,
                            Y = 20
                        },
                        new
                        {
                            Id = new Guid("c6ede385-b310-467c-a89c-68671b29c78c"),
                            AnimationStateId = new Guid("76897c6a-1fc6-44e0-b426-ab78adbddec0"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 1,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 899, DateTimeKind.Utc).AddTicks(7368),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 25,
                            Y = 82
                        },
                        new
                        {
                            Id = new Guid("28c19f33-30c0-4b52-b5a4-a3165c756559"),
                            AnimationStateId = new Guid("76897c6a-1fc6-44e0-b426-ab78adbddec0"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 2,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 899, DateTimeKind.Utc).AddTicks(8999),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 25,
                            Y = 148
                        },
                        new
                        {
                            Id = new Guid("151703ff-1ec2-4a26-a2cd-a7865841eef9"),
                            AnimationStateId = new Guid("76897c6a-1fc6-44e0-b426-ab78adbddec0"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 3,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 900, DateTimeKind.Utc).AddTicks(680),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 25,
                            Y = 212
                        },
                        new
                        {
                            Id = new Guid("d69e5134-ef98-4231-9743-71ee24de5dec"),
                            AnimationStateId = new Guid("76897c6a-1fc6-44e0-b426-ab78adbddec0"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 4,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 900, DateTimeKind.Utc).AddTicks(2291),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 25,
                            Y = 276
                        },
                        new
                        {
                            Id = new Guid("385cc967-b3c7-40bd-89bc-d251ccad8cbe"),
                            AnimationStateId = new Guid("76897c6a-1fc6-44e0-b426-ab78adbddec0"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 5,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 900, DateTimeKind.Utc).AddTicks(3900),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 25,
                            Y = 338
                        },
                        new
                        {
                            Id = new Guid("130b1ddd-74a2-4774-b001-9770ef9a0d5e"),
                            AnimationStateId = new Guid("76897c6a-1fc6-44e0-b426-ab78adbddec0"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 6,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 900, DateTimeKind.Utc).AddTicks(5535),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 25,
                            Y = 404
                        },
                        new
                        {
                            Id = new Guid("b7964fb7-4a77-4037-9bc0-fb5ac134adc2"),
                            AnimationStateId = new Guid("76897c6a-1fc6-44e0-b426-ab78adbddec0"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 7,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 900, DateTimeKind.Utc).AddTicks(7582),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 25,
                            Y = 468
                        },
                        new
                        {
                            Id = new Guid("3dea5627-026e-4975-85ed-ea75ccde373b"),
                            AnimationStateId = new Guid("76897c6a-1fc6-44e0-b426-ab78adbddec0"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 8,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 901, DateTimeKind.Utc).AddTicks(246),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 25,
                            Y = 533
                        },
                        new
                        {
                            Id = new Guid("6349d61b-d220-4604-9b3c-17ef175e1eeb"),
                            AnimationStateId = new Guid("76897c6a-1fc6-44e0-b426-ab78adbddec0"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 9,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 901, DateTimeKind.Utc).AddTicks(2905),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 25,
                            Y = 597
                        },
                        new
                        {
                            Id = new Guid("c9ab1500-f3c5-426d-8aeb-b0da09e34254"),
                            AnimationStateId = new Guid("76897c6a-1fc6-44e0-b426-ab78adbddec0"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 10,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 901, DateTimeKind.Utc).AddTicks(4576),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 25,
                            Y = 660
                        },
                        new
                        {
                            Id = new Guid("2395382d-1f60-4296-8615-fff96d4c708b"),
                            AnimationStateId = new Guid("76897c6a-1fc6-44e0-b426-ab78adbddec0"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 11,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 901, DateTimeKind.Utc).AddTicks(6196),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 25,
                            Y = 724
                        },
                        new
                        {
                            Id = new Guid("98b482a0-99e1-415a-9061-ac2c7bea60af"),
                            AnimationStateId = new Guid("4f97aeac-eb45-43ad-8ff6-7b50f76b1114"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 0,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 901, DateTimeKind.Utc).AddTicks(9531),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 25,
                            Y = 275
                        },
                        new
                        {
                            Id = new Guid("dd703caa-2184-4988-8251-5b15fa96c2e3"),
                            AnimationStateId = new Guid("4f97aeac-eb45-43ad-8ff6-7b50f76b1114"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 1,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 902, DateTimeKind.Utc).AddTicks(1140),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 90,
                            Y = 275
                        },
                        new
                        {
                            Id = new Guid("d9479124-2d71-4a5f-a6f8-779bd6290a6e"),
                            AnimationStateId = new Guid("4f97aeac-eb45-43ad-8ff6-7b50f76b1114"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 2,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 902, DateTimeKind.Utc).AddTicks(2858),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 154,
                            Y = 275
                        },
                        new
                        {
                            Id = new Guid("745c2e34-fe9b-4fdb-9d71-fcf5ed79b48a"),
                            AnimationStateId = new Guid("4f97aeac-eb45-43ad-8ff6-7b50f76b1114"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 3,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 902, DateTimeKind.Utc).AddTicks(4451),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 218,
                            Y = 275
                        },
                        new
                        {
                            Id = new Guid("d60aadf5-b15f-440f-ae1e-e79c1c08bb95"),
                            AnimationStateId = new Guid("4f97aeac-eb45-43ad-8ff6-7b50f76b1114"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 4,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 902, DateTimeKind.Utc).AddTicks(6125),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 281,
                            Y = 275
                        },
                        new
                        {
                            Id = new Guid("b624fce4-7dcf-4a30-98b3-1404a3abb50b"),
                            AnimationStateId = new Guid("4f97aeac-eb45-43ad-8ff6-7b50f76b1114"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 5,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 902, DateTimeKind.Utc).AddTicks(7737),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 345,
                            Y = 275
                        },
                        new
                        {
                            Id = new Guid("f0f2425c-18de-4434-92cc-a7fb82a19741"),
                            AnimationStateId = new Guid("4f97aeac-eb45-43ad-8ff6-7b50f76b1114"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 6,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 902, DateTimeKind.Utc).AddTicks(9314),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 410,
                            Y = 275
                        },
                        new
                        {
                            Id = new Guid("010c5437-9399-4953-94ce-f25f1c263e7f"),
                            AnimationStateId = new Guid("4f97aeac-eb45-43ad-8ff6-7b50f76b1114"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 7,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 903, DateTimeKind.Utc).AddTicks(899),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 473,
                            Y = 275
                        },
                        new
                        {
                            Id = new Guid("25f7a155-ec99-4bdb-bc77-fda40502c12a"),
                            AnimationStateId = new Guid("98bb3714-f46d-47a1-b5d8-804565647227"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 0,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 903, DateTimeKind.Utc).AddTicks(4164),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 25,
                            Y = 338
                        },
                        new
                        {
                            Id = new Guid("1e497989-da17-4324-afd6-77c5b09b6167"),
                            AnimationStateId = new Guid("98bb3714-f46d-47a1-b5d8-804565647227"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 1,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 903, DateTimeKind.Utc).AddTicks(5758),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 90,
                            Y = 338
                        },
                        new
                        {
                            Id = new Guid("559cacb0-72e8-41d7-b221-127242ca39bf"),
                            AnimationStateId = new Guid("98bb3714-f46d-47a1-b5d8-804565647227"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 2,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 903, DateTimeKind.Utc).AddTicks(7346),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 154,
                            Y = 338
                        },
                        new
                        {
                            Id = new Guid("055272cb-2615-4721-be49-149b84ae251c"),
                            AnimationStateId = new Guid("98bb3714-f46d-47a1-b5d8-804565647227"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 3,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 903, DateTimeKind.Utc).AddTicks(8959),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 218,
                            Y = 338
                        },
                        new
                        {
                            Id = new Guid("ae21cf26-be09-4992-ae5f-e7d002d9f9b5"),
                            AnimationStateId = new Guid("98bb3714-f46d-47a1-b5d8-804565647227"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 4,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 904, DateTimeKind.Utc).AddTicks(541),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 281,
                            Y = 338
                        },
                        new
                        {
                            Id = new Guid("1809c8e0-3486-4fc9-a082-bf72ceaaab3b"),
                            AnimationStateId = new Guid("98bb3714-f46d-47a1-b5d8-804565647227"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 5,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 904, DateTimeKind.Utc).AddTicks(2193),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 346,
                            Y = 338
                        },
                        new
                        {
                            Id = new Guid("2a8b3f4f-a566-46de-8405-a6a8781a10a5"),
                            AnimationStateId = new Guid("98bb3714-f46d-47a1-b5d8-804565647227"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 6,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 904, DateTimeKind.Utc).AddTicks(3786),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 410,
                            Y = 338
                        },
                        new
                        {
                            Id = new Guid("e494b591-8e92-4bc2-9fbb-d67ae6bd2c95"),
                            AnimationStateId = new Guid("98bb3714-f46d-47a1-b5d8-804565647227"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 7,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 904, DateTimeKind.Utc).AddTicks(5412),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 474,
                            Y = 338
                        },
                        new
                        {
                            Id = new Guid("de68a979-83f4-4ccc-ac3f-5c018f7ad641"),
                            AnimationStateId = new Guid("82b4d763-783b-4021-adca-8006ca1dba9b"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 0,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 904, DateTimeKind.Utc).AddTicks(8612),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 25,
                            Y = 404
                        },
                        new
                        {
                            Id = new Guid("391019ae-3c07-40cd-99b2-6813f517a400"),
                            AnimationStateId = new Guid("82b4d763-783b-4021-adca-8006ca1dba9b"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 1,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 905, DateTimeKind.Utc).AddTicks(266),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 90,
                            Y = 404
                        },
                        new
                        {
                            Id = new Guid("21275474-2e63-4e62-bc6f-0e9d375f378d"),
                            AnimationStateId = new Guid("82b4d763-783b-4021-adca-8006ca1dba9b"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 2,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 905, DateTimeKind.Utc).AddTicks(1858),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 154,
                            Y = 404
                        },
                        new
                        {
                            Id = new Guid("0528dfa5-271c-4475-8a10-b0a908c697fc"),
                            AnimationStateId = new Guid("82b4d763-783b-4021-adca-8006ca1dba9b"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 3,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 905, DateTimeKind.Utc).AddTicks(3442),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 218,
                            Y = 404
                        },
                        new
                        {
                            Id = new Guid("dd08ff79-e232-4b73-bc73-1548618544ae"),
                            AnimationStateId = new Guid("82b4d763-783b-4021-adca-8006ca1dba9b"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 4,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 905, DateTimeKind.Utc).AddTicks(5014),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 281,
                            Y = 404
                        },
                        new
                        {
                            Id = new Guid("b81ef14b-d078-4e91-b05d-4e543c7e0104"),
                            AnimationStateId = new Guid("82b4d763-783b-4021-adca-8006ca1dba9b"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 5,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 905, DateTimeKind.Utc).AddTicks(6668),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 346,
                            Y = 404
                        },
                        new
                        {
                            Id = new Guid("a4ba807d-e744-4e73-86b3-ec1309de8806"),
                            AnimationStateId = new Guid("82b4d763-783b-4021-adca-8006ca1dba9b"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 6,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 905, DateTimeKind.Utc).AddTicks(8263),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 410,
                            Y = 404
                        },
                        new
                        {
                            Id = new Guid("7640a2f2-b60b-4127-89bb-db53db2cd82a"),
                            AnimationStateId = new Guid("82b4d763-783b-4021-adca-8006ca1dba9b"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 7,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 905, DateTimeKind.Utc).AddTicks(9860),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 474,
                            Y = 404
                        },
                        new
                        {
                            Id = new Guid("d45ded90-4089-4211-8fea-63076d65e8af"),
                            AnimationStateId = new Guid("c5e30e70-49b3-41dd-8810-c22f7fb65241"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 0,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 906, DateTimeKind.Utc).AddTicks(3159),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 26,
                            Y = 468
                        },
                        new
                        {
                            Id = new Guid("91ca3ff5-1932-4414-98b5-1cb6c9e73782"),
                            AnimationStateId = new Guid("c5e30e70-49b3-41dd-8810-c22f7fb65241"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 1,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 906, DateTimeKind.Utc).AddTicks(4818),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 90,
                            Y = 467
                        },
                        new
                        {
                            Id = new Guid("1d3dc136-4cde-4896-bbe9-6ae20a5ee272"),
                            AnimationStateId = new Guid("c5e30e70-49b3-41dd-8810-c22f7fb65241"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 2,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 906, DateTimeKind.Utc).AddTicks(6423),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 153,
                            Y = 468
                        },
                        new
                        {
                            Id = new Guid("a8e4700e-8d0d-4bcb-9dc8-c91277da4f96"),
                            AnimationStateId = new Guid("c5e30e70-49b3-41dd-8810-c22f7fb65241"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 3,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 906, DateTimeKind.Utc).AddTicks(8008),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 218,
                            Y = 468
                        },
                        new
                        {
                            Id = new Guid("9728671e-0fed-4216-be4d-a9261c6fdb68"),
                            AnimationStateId = new Guid("c5e30e70-49b3-41dd-8810-c22f7fb65241"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 4,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 906, DateTimeKind.Utc).AddTicks(9589),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 282,
                            Y = 468
                        },
                        new
                        {
                            Id = new Guid("335735d3-ee1c-46d9-94f1-b2979856bb34"),
                            AnimationStateId = new Guid("c5e30e70-49b3-41dd-8810-c22f7fb65241"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 5,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 907, DateTimeKind.Utc).AddTicks(1177),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 346,
                            Y = 468
                        },
                        new
                        {
                            Id = new Guid("9bb6e0d7-9fdf-4a0b-9005-a014f0eda6de"),
                            AnimationStateId = new Guid("c5e30e70-49b3-41dd-8810-c22f7fb65241"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 6,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 907, DateTimeKind.Utc).AddTicks(2845),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 409,
                            Y = 468
                        },
                        new
                        {
                            Id = new Guid("4e738615-653b-4bf7-bc01-a36c1027c016"),
                            AnimationStateId = new Guid("c5e30e70-49b3-41dd-8810-c22f7fb65241"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Index = 7,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 907, DateTimeKind.Utc).AddTicks(4436),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            W = 14,
                            X = 474,
                            Y = 468
                        });
                });

            modelBuilder.Entity("Entities.AvatarManagement.Avatar", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Change")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<int>("H")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Insertion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 9, 26, 17, 56, 8, 893, DateTimeKind.Local).AddTicks(4295));

                    b.Property<Guid?>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<Guid?>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<string>("Src")
                        .HasColumnType("text");

                    b.Property<int>("V")
                        .HasColumnType("integer");

                    b.Property<int>("W")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Avatar");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d609e9e5-0ce2-4e52-86a8-0fc0455955c7"),
                            Change = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            H = 24,
                            Insertion = new DateTime(2021, 9, 26, 20, 56, 8, 895, DateTimeKind.Utc).AddTicks(9482),
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PublisherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Src = "profile",
                            V = 1,
                            W = 14
                        });
                });

            modelBuilder.Entity("Entities.Public.ChangeRecord", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Change")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<DateTime>("Insertion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 9, 26, 17, 56, 8, 891, DateTimeKind.Local).AddTicks(1374));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecordIdentifier")
                        .HasColumnType("uuid");

                    b.Property<string>("SerializedCurrent")
                        .HasColumnType("text");

                    b.Property<string>("SerializedPrevious")
                        .HasColumnType("text");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("ChangeRecord");
                });

            modelBuilder.Entity("Entities.Public.ChangeRecordTracker", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Change")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ChangeRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Insertion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 9, 26, 17, 56, 8, 892, DateTimeKind.Local).AddTicks(5190));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecordIdentifier")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRecordId");

                    b.ToTable("ChangeRecordTracker");
                });

            modelBuilder.Entity("Entities.AvatarManagement.Animation", b =>
                {
                    b.HasOne("Entities.AvatarManagement.Avatar", "Avatar")
                        .WithMany("AnimationCollection")
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("Entities.AvatarManagement.AnimationState", b =>
                {
                    b.HasOne("Entities.AvatarManagement.Animation", "Animation")
                        .WithMany("AnimationStateCollection")
                        .HasForeignKey("AnimationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animation");
                });

            modelBuilder.Entity("Entities.AvatarManagement.AnimationStateItem", b =>
                {
                    b.HasOne("Entities.AvatarManagement.AnimationState", "AnimationState")
                        .WithMany("AnimationStateItemCollection")
                        .HasForeignKey("AnimationStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimationState");
                });

            modelBuilder.Entity("Entities.Public.ChangeRecordTracker", b =>
                {
                    b.HasOne("Entities.Public.ChangeRecord", "ChangeRecord")
                        .WithMany()
                        .HasForeignKey("ChangeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeRecord");
                });

            modelBuilder.Entity("Entities.AvatarManagement.Animation", b =>
                {
                    b.Navigation("AnimationStateCollection");
                });

            modelBuilder.Entity("Entities.AvatarManagement.AnimationState", b =>
                {
                    b.Navigation("AnimationStateItemCollection");
                });

            modelBuilder.Entity("Entities.AvatarManagement.Avatar", b =>
                {
                    b.Navigation("AnimationCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
