// <auto-generated />
using System;
using Backend.Infra.Identity.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20231016211823_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Infra.Api.ChangeRecord.ChangeRecord", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Change")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Insertion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2023, 10, 16, 18, 18, 22, 823, DateTimeKind.Local).AddTicks(2621));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecordIdentifier")
                        .HasColumnType("uuid");

                    b.Property<string>("SerializedCurrent")
                        .HasColumnType("text");

                    b.Property<string>("SerializedPrevious")
                        .HasColumnType("text");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("ChangeRecord", "public");
                });

            modelBuilder.Entity("Backend.Infra.Api.ChangeRecord.ChangeRecordTracker", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Change")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangeRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Insertion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2023, 10, 16, 18, 18, 22, 823, DateTimeKind.Local).AddTicks(3085));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecordIdentifier")
                        .HasColumnType("uuid");

                    b.Property<string>("SerializedCurrentHash")
                        .HasColumnType("text");

                    b.Property<string>("SerializedPreviousHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRecordId");

                    b.ToTable("ChangeRecordTracker", "public");
                });

            modelBuilder.Entity("Backend.Infra.Identity.Documents.Document.Document", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Change")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Insertion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2023, 10, 16, 18, 18, 22, 823, DateTimeKind.Local).AddTicks(5506));

                    b.Property<Guid?>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<Guid?>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Document", "public");
                });

            modelBuilder.Entity("Backend.Infra.Identity.Documents.DocumentType.DocumentType", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Change")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Insertion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfDigits")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b98d98be-885e-4454-8b0e-5c6a29f06df8"),
                            Hash = "2a2d91ff4e16560d2c0f00730eaa4b1df377ac636fc6a209feeed7f91be53ec88f4fc016bafeccc8a21fedf09a05596a5d27fffc56c3a7e0e9c83948231454e5",
                            Insertion = new DateTime(2023, 10, 16, 18, 18, 22, 823, DateTimeKind.Local).AddTicks(6423),
                            Name = "CPF",
                            NumberOfDigits = 11,
                            OwnerId = new Guid("8d3aa60b-cd64-40f7-ba97-4f4a6a3ba6d2"),
                            PublisherId = new Guid("6d9b54f4-f5bf-412b-aa2a-20b7c24f9ede"),
                            State = true
                        },
                        new
                        {
                            Id = new Guid("e6af6086-09e4-4d1f-826a-8f386fbb823e"),
                            Hash = "7c20402d95f250a8f2a9926cb0bd0199d327f74cf7a1bfe82c17acc29c2f942e101cefc4d1976bee455f6403594ef20b59a989e72abffe0d8e59f20d341abbff",
                            Insertion = new DateTime(2023, 10, 16, 18, 18, 22, 823, DateTimeKind.Local).AddTicks(6432),
                            Name = "RG",
                            NumberOfDigits = 9,
                            OwnerId = new Guid("8d3aa60b-cd64-40f7-ba97-4f4a6a3ba6d2"),
                            PublisherId = new Guid("6d9b54f4-f5bf-412b-aa2a-20b7c24f9ede"),
                            State = true
                        },
                        new
                        {
                            Id = new Guid("011c80a8-7998-41a6-a934-9b9a7959e4f3"),
                            Hash = "45a83b33ffa6a81f298f0c61116221679a007fefd289959d096aff89b0e97999bfac53cc3596e2716d739ca08ca0b0b0c63b8d6a23f4da12b37f71b1ef287f1f",
                            Insertion = new DateTime(2023, 10, 16, 18, 18, 22, 823, DateTimeKind.Local).AddTicks(6434),
                            Name = "CNPJ",
                            NumberOfDigits = 14,
                            OwnerId = new Guid("8d3aa60b-cd64-40f7-ba97-4f4a6a3ba6d2"),
                            PublisherId = new Guid("6d9b54f4-f5bf-412b-aa2a-20b7c24f9ede"),
                            State = true
                        },
                        new
                        {
                            Id = new Guid("782a6bc0-98fb-44f9-acce-d3e33d7314b7"),
                            Hash = "71398755ecedb397cc5322af263e41a13d499e765a870ceac82278432e00345774a48b1b23f430709b22062297eab2dad353b275a15a976dbb0d71f831962f02",
                            Insertion = new DateTime(2023, 10, 16, 18, 18, 22, 823, DateTimeKind.Local).AddTicks(6436),
                            Name = "CNH",
                            NumberOfDigits = 10,
                            OwnerId = new Guid("8d3aa60b-cd64-40f7-ba97-4f4a6a3ba6d2"),
                            PublisherId = new Guid("6d9b54f4-f5bf-412b-aa2a-20b7c24f9ede"),
                            State = true
                        });
                });

            modelBuilder.Entity("Backend.Infra.Identity.Profile.Profile", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Change")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<string>("HashAuth")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Insertion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2023, 10, 16, 18, 18, 22, 823, DateTimeKind.Local).AddTicks(4191));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<Guid?>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<string[]>("Role")
                        .HasColumnType("text[]");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Profile", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d3aa60b-cd64-40f7-ba97-4f4a6a3ba6d2"),
                            Email = "cfs.plus.s8@gmail.com",
                            Hash = "63abf25852e5a2fca00e5c846fb7b6dcaa1bd8d90678adf9046fdbb39666250eb3e110fd1fcb415c81eb7bb6c78b58ec03a3721381f68a3f6434c7bb8f0aa416",
                            HashAuth = "MjlEOTJFQkYzQUU1MTFCMkQ0M0Y4MjYwRjFBQUQ1NTA3QjM5MzRDQkY5RkExQzVGQjgwQTAzNDY5RkU4NjIzMjM3NjUxNzQ5MTZBNkRENERDQjMzQkUzQTE1NkEzMTgxM0FGQ0EyRkM0ODY2QTU1N0U5M0QwNUJFQTM2QTQ3OUY=",
                            Name = "admin",
                            Password = "MTIzQGFscGhh",
                            Role = new[] { "ADMIN" },
                            State = false
                        },
                        new
                        {
                            Id = new Guid("fb2dcb04-aca2-4e61-9e87-75683160ff99"),
                            Email = "publisher.profile@gmail.com",
                            Hash = "808a247df9383f79fcf55eccdc4091f9a89a8774783d4e08e5b1db4c9ba21b32da5fd9f8fb7f0508c03496c3269c121aa3e89fc81dd61219a3e42ca423f79e06",
                            HashAuth = "MEM5Q0U3MDVDNjY0MEM3Rjc4QkEwOUVBNkFERUYwQTA2NjBDOENERDJFMzBGREU3OUEzODBBNjI1RjkyNThEM0M2REIxOTA4QjE4Rjk3RThEMDk2RkQ0QjAxRkQxRUI1MzAxNDYyMDJGRjU2RkY0NEE0MjhBRjAxRjNGN0Q2Q0E=",
                            Name = "publisher.profile",
                            OwnerId = new Guid("8d3aa60b-cd64-40f7-ba97-4f4a6a3ba6d2"),
                            Password = "ZDZmN2E0YTUtNzY4NC00ZjFhLTk0ZGEtNjczZjU5ZTFhMDI5",
                            PublisherId = new Guid("8d3aa60b-cd64-40f7-ba97-4f4a6a3ba6d2"),
                            Role = new[] { "PUBLISHER" },
                            State = false
                        },
                        new
                        {
                            Id = new Guid("2ad011a7-0448-4fa0-ac4a-0b0f7b3a736b"),
                            Email = "publisher.rc@gmail.com",
                            Hash = "d647cc4eea25c0791249229c6c3e098405a937f9f54c22362d490dbd178f41c98a57360bd6bb005c3f397ae9e88669669b5d6c8a6983954f2e3643feb188e3fc",
                            HashAuth = "QTI5RTdENDFBMkRDQjFDQTk2MTU1NEJFMjkwMTY1MkRFODQzNEI1Q0E3NkMyMUQ2NEE3RkQyMzU1QkU5ODQ5MDlGMEY0MENBQjZFMjQ1MDdEQ0QwQTQ2RUExQjkwRkQ3QzFCQTZENTg2OEYyRTY1NjIxMUFDRTA0QkE0NTg3OTE=",
                            Name = "publisher.rc",
                            OwnerId = new Guid("8d3aa60b-cd64-40f7-ba97-4f4a6a3ba6d2"),
                            Password = "MDk5MWY5NjAtY2YyNi00MWQ1LWEzZWUtN2Q4YWFhODhiY2Jk",
                            PublisherId = new Guid("fb2dcb04-aca2-4e61-9e87-75683160ff99"),
                            Role = new[] { "PUBLISHER" },
                            State = false
                        },
                        new
                        {
                            Id = new Guid("45dc7df1-f19e-4e02-84da-5d3c5ba4de2b"),
                            Email = "publisher.rct@gmail.com",
                            Hash = "eea1320abd8ed939999c55d26b2507497aebc2df93a49dfff55f5126d93418e6def2220950a73d3e798442dcdc9ae0cf24922559edd598e172bf433057724f60",
                            HashAuth = "QzY2MzI1REYyM0JBREM4MEY2MEI2OEY4MDU2QjgwRDg4OTI1NzhDNTA4RjczRENDMzI3MDZDN0M1MEI4MjMzMzM0QTBEMjcxRDIyQUMwODMxMDM5NDI4NUVGMDk0MTMxMkFGRTIwMkUxMjUzQTEwMzhCRDVDNkU0MDI3QUIxNTI=",
                            Name = "publisher.rct",
                            OwnerId = new Guid("8d3aa60b-cd64-40f7-ba97-4f4a6a3ba6d2"),
                            Password = "OWQ5NDk2ZjctYmZjYy00Y2RlLTgwNzQtYzQxNDlmZjllMTc4",
                            PublisherId = new Guid("fb2dcb04-aca2-4e61-9e87-75683160ff99"),
                            Role = new[] { "PUBLISHER" },
                            State = false
                        },
                        new
                        {
                            Id = new Guid("e8b38b60-122b-4e96-8fe2-6b2bc0dbc557"),
                            Email = "publisher.session@gmail.com",
                            Hash = "bdeea16a0998befcc15399d72985c5efeea7d630627dbdeb1148cc5686abaf8c531162f48de8f7afadaa6a530ea110c85334da418ed4808013cd4f543c03a676",
                            HashAuth = "Njg4NTk4QTgzNDUwRDQ4MTUyM0IzQjdGNUNERDNCQTUwMDFBM0Q3QTkwNDMyNURBMTcxM0NFRjM2NEU3NjcyNDlCN0ZEMTUyRDFCNTM4NDRFNjg4MkI1NzdCMkJEOURGNENBNDkwREVGNTc0MUU5REIwOTZENTQ3NUU1OTgxQ0U=",
                            Name = "publisher.session",
                            OwnerId = new Guid("8d3aa60b-cd64-40f7-ba97-4f4a6a3ba6d2"),
                            Password = "ZjIyYThiZWItYTUzOS00ZmQ2LTk1MGEtMDc1NGNhMjkxYWJk",
                            PublisherId = new Guid("fb2dcb04-aca2-4e61-9e87-75683160ff99"),
                            Role = new[] { "PUBLISHER" },
                            State = false
                        },
                        new
                        {
                            Id = new Guid("d0b5e951-2257-4e2e-8be1-bfa4b2b6b640"),
                            Email = "publisher.doc@gmail.com",
                            Hash = "5a8958d3ed78596a9bda88797bebbb43eb2f3abf67ff8dd271750cafffa354be3639c45d26a0d5901a183fbc34648da8f082ac8fc6b0eed033af36b14e324e3c",
                            HashAuth = "MEU3MDQ2QTlCNzIwRDZCREI2MjczMzFDNTdFQjE3MUI1QTdCRjhDMzRGMDQxQTc1OTBDQjQwQzFFRjZFMTFEMEU2RDRGNTI0MzA5REVERkIxOUM3MTU1NTU1NkYxREFBNzU2RDc3MkE4NTEwODc5NTdEQUQzQUI0QzYzRjhCNDQ=",
                            Name = "publisher.doc",
                            OwnerId = new Guid("8d3aa60b-cd64-40f7-ba97-4f4a6a3ba6d2"),
                            Password = "MmFiY2QwMzItYzg2Yi00N2MyLTljNzMtZDU5NWQxZWIzMzA1",
                            PublisherId = new Guid("fb2dcb04-aca2-4e61-9e87-75683160ff99"),
                            Role = new[] { "PUBLISHER" },
                            State = false
                        },
                        new
                        {
                            Id = new Guid("6d9b54f4-f5bf-412b-aa2a-20b7c24f9ede"),
                            Email = "publisher.doc.type@gmail.com",
                            Hash = "bb7f67f435b7c9bb360af6508a1276f8bf8d9861cf5820c8f459d1c034617ef354d40b88df141f44849517f9f40cdf1836ccea990ba3f19b0c0fe5fa5dab736b",
                            HashAuth = "RjExQjQwNUU3NUIzNDA5QzRBNTY4MDgzNkY1Rjc1Q0FCN0Y4OTNCRDY2NzVFNEZFMzIzRjhBQTYzMzk5OTJBQjA1RDNGNTVCNEI2NzE4Qzg0NUIwMUQ5RDlDMzAwNzMwMzk5RUYyMjdDNTZEQTczNkRCNDE0MTA3MDEzNUFCMDc=",
                            Name = "publisher.doc.type",
                            OwnerId = new Guid("8d3aa60b-cd64-40f7-ba97-4f4a6a3ba6d2"),
                            Password = "ZmU2OGE1OGUtZWQ4Yi00OTlhLWI5M2ItN2ZiOTA1OWU1MDlk",
                            PublisherId = new Guid("fb2dcb04-aca2-4e61-9e87-75683160ff99"),
                            Role = new[] { "PUBLISHER" },
                            State = false
                        });
                });

            modelBuilder.Entity("Backend.Infra.Identity.Session.Session", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Change")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Insertion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Session", "public");
                });

            modelBuilder.Entity("Backend.Infra.Api.ChangeRecord.ChangeRecordTracker", b =>
                {
                    b.HasOne("Backend.Infra.Api.ChangeRecord.ChangeRecord", "ChangeRecord")
                        .WithMany()
                        .HasForeignKey("ChangeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeRecord");
                });

            modelBuilder.Entity("Backend.Infra.Identity.Documents.Document.Document", b =>
                {
                    b.HasOne("Backend.Infra.Identity.Documents.DocumentType.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");
                });
#pragma warning restore 612, 618
        }
    }
}
